// Sample Support Tickets Data
export const supportTickets = [
    {
        id: 1,
        ticketNumber: "SP-2025-001",
        customerId: "CUS-001",
        customerName: "Emmanuel Johnson",
        customerEmail: "ejohnson@example.com",
        customerPhone: "+234 801 234 5678",
        subject: "Payment not reflected in account",
        description: "I made a payment of ₦150,000 for my booking but it's not showing in my account. Transaction reference: TRX-20250105-001",
        priority: "High",
        status: "Open",
        category: "Payment",
        assignedTo: "AG-001",
        assignedAgent: "Sarah Okafor",
        tags: ["payment", "urgent"],
        createdAt: "2025-01-05T08:30:00",
        updatedAt: "2025-01-05T08:30:00",
        lastActivity: "2025-01-05T08:30:00",
        isEscalated: false,
        responseTime: null,
        resolutionTime: null
    },
    {
        id: 2,
        ticketNumber: "SP-2025-002",
        customerId: "CUS-002",
        customerName: "Grace Eze",
        customerEmail: "geze@example.com",
        customerPhone: "+234 802 345 6789",
        subject: "Unable to access my bookings",
        description: "I can't see my past bookings on the platform. Getting an error message when I try to view them.",
        priority: "Medium",
        status: "In Progress",
        category: "Technical",
        assignedTo: "AG-002",
        assignedAgent: "John Adebayo",
        tags: ["technical", "bug"],
        createdAt: "2025-01-04T14:20:00",
        updatedAt: "2025-01-05T09:15:00",
        lastActivity: "2025-01-05T09:15:00",
        isEscalated: false,
        responseTime: "2 hours",
        resolutionTime: null
    },
    {
        id: 3,
        ticketNumber: "SP-2025-003",
        customerId: "CUS-003",
        customerName: "Fatima Hassan",
        customerEmail: "fhassan@example.com",
        customerPhone: "+234 803 456 7890",
        subject: "Vendor cancelled booking without notice",
        description: "My booking with Luxury Car Rentals was cancelled last minute without any explanation. Order #ORD-2025-008",
        priority: "Urgent",
        status: "In Progress",
        category: "General",
        assignedTo: "AG-001",
        assignedAgent: "Sarah Okafor",
        tags: ["vendor-issue", "urgent", "refund"],
        createdAt: "2025-01-05T07:00:00",
        updatedAt: "2025-01-05T10:30:00",
        lastActivity: "2025-01-05T10:30:00",
        isEscalated: true,
        escalatedAt: "2025-01-05T09:00:00",
        responseTime: "30 minutes",
        resolutionTime: null
    },
    {
        id: 4,
        ticketNumber: "SP-2025-004",
        customerId: "CUS-004",
        customerName: "David Okonkwo",
        customerEmail: "dokonkwo@example.com",
        customerPhone: "+234 804 567 8901",
        subject: "Incorrect billing amount",
        description: "I was charged ₦200,000 but my booking was for ₦150,000. Please review and refund the difference.",
        priority: "High",
        status: "Pending",
        category: "Billing",
        assignedTo: "AG-003",
        assignedAgent: "Michael Benson",
        tags: ["billing", "refund"],
        createdAt: "2025-01-04T16:45:00",
        updatedAt: "2025-01-05T08:00:00",
        lastActivity: "2025-01-05T08:00:00",
        isEscalated: false,
        responseTime: "1 hour",
        resolutionTime: null
    },
    {
        id: 5,
        ticketNumber: "SP-2025-005",
        customerId: "CUS-005",
        customerName: "Amina Yusuf",
        customerEmail: "ayusuf@example.com",
        customerPhone: "+234 805 678 9012",
        subject: "How to change email address",
        description: "I want to update my email address on my account. Can you help me with that?",
        priority: "Low",
        status: "Resolved",
        category: "Account",
        assignedTo: "AG-002",
        assignedAgent: "John Adebayo",
        tags: ["account", "simple"],
        createdAt: "2025-01-03T11:00:00",
        updatedAt: "2025-01-03T13:30:00",
        lastActivity: "2025-01-03T13:30:00",
        resolvedAt: "2025-01-03T13:30:00",
        isEscalated: false,
        responseTime: "15 minutes",
        resolutionTime: "2.5 hours",
        satisfaction: 5
    },
    {
        id: 6,
        ticketNumber: "SP-2025-006",
        customerId: "CUS-006",
        customerName: "Chidi Nnadi",
        customerEmail: "cnnadi@example.com",
        customerPhone: "+234 806 789 0123",
        subject: "Refund request for cancelled order",
        description: "I cancelled my order ORD-2025-010 and need a refund. It's been 5 days and I haven't received it.",
        priority: "Medium",
        status: "Resolved",
        category: "Billing",
        assignedTo: "AG-003",
        assignedAgent: "Michael Benson",
        tags: ["refund", "resolved"],
        createdAt: "2025-01-02T09:30:00",
        updatedAt: "2025-01-04T15:20:00",
        lastActivity: "2025-01-04T15:20:00",
        resolvedAt: "2025-01-04T15:20:00",
        isEscalated: false,
        responseTime: "45 minutes",
        resolutionTime: "2 days",
        satisfaction: 4
    },
    {
        id: 7,
        ticketNumber: "SP-2025-007",
        customerId: "CUS-007",
        customerName: "Blessing Okoro",
        customerEmail: "bokoro@example.com",
        customerPhone: "+234 807 890 1234",
        subject: "Vendor not responding to messages",
        description: "I've been trying to contact Premier Catering Services about my upcoming event but they're not responding.",
        priority: "Medium",
        status: "Open",
        category: "General",
        assignedTo: null,
        assignedAgent: null,
        tags: ["vendor-communication"],
        createdAt: "2025-01-05T11:00:00",
        updatedAt: "2025-01-05T11:00:00",
        lastActivity: "2025-01-05T11:00:00",
        isEscalated: false,
        responseTime: null,
        resolutionTime: null
    },
    {
        id: 8,
        ticketNumber: "SP-2025-008",
        customerId: "CUS-008",
        customerName: "Tunde Adeyemi",
        customerEmail: "tadeyemi@example.com",
        customerPhone: "+234 808 901 2345",
        subject: "Request to delete my account",
        description: "I no longer use this platform and would like to delete my account and all associated data.",
        priority: "Low",
        status: "Closed",
        category: "Account",
        assignedTo: "AG-001",
        assignedAgent: "Sarah Okafor",
        tags: ["account-deletion", "gdpr"],
        createdAt: "2024-12-28T10:00:00",
        updatedAt: "2025-01-02T14:00:00",
        lastActivity: "2025-01-02T14:00:00",
        resolvedAt: "2025-01-02T14:00:00",
        isEscalated: false,
        responseTime: "1 hour",
        resolutionTime: "5 days",
        satisfaction: 5
    }
];

// Support Agents
export const supportAgents = [
    {
        id: "AG-001",
        name: "Sarah Okafor",
        email: "sokafor@synkkafrica.com",
        role: "Senior Support Agent",
        avatar: "https://randomuser.me/api/portraits/women/44.jpg",
        status: "available",
        assignedTickets: 3,
        resolvedToday: 5,
        avgResponseTime: "25 minutes",
        satisfaction: 4.8
    },
    {
        id: "AG-002",
        name: "John Adebayo",
        email: "jadebayo@synkkafrica.com",
        role: "Support Agent",
        avatar: "https://randomuser.me/api/portraits/men/52.jpg",
        status: "busy",
        assignedTickets: 2,
        resolvedToday: 3,
        avgResponseTime: "35 minutes",
        satisfaction: 4.6
    },
    {
        id: "AG-003",
        name: "Michael Benson",
        email: "mbenson@synkkafrica.com",
        role: "Support Agent",
        avatar: "https://randomuser.me/api/portraits/men/67.jpg",
        status: "available",
        assignedTickets: 2,
        resolvedToday: 4,
        avgResponseTime: "30 minutes",
        satisfaction: 4.7
    }
];

export const ticketCategories = [
    "General",
    "Payment",
    "Technical",
    "Billing",
    "Account",
    "Vendor Issue",
    "Refund Request"
];

export const ticketPriorities = [
    "Low",
    "Medium",
    "High",
    "Urgent"
];

export const ticketStatuses = [
    "Open",
    "In Progress",
    "Pending",
    "Resolved",
    "Closed"
];
