"use client";
// Sample vendor data
export const vendors = [
  {
    id: 'VND-001',
    businessName: 'Safari Adventures Ltd',
    ownerName: 'John Okeke',
    email: 'john@safariventures.com',
    phone: '+234 801 234 5678',
    category: 'Tours & Travel',
    location: 'Lagos, Nigeria',
    onboardingDate: '2024-10-15',
    status: 'Pending Approval',
    verificationStatus: 'Documents Submitted',
    totalListings: 0,
    completionPercentage: 100,
    businessDocument: 'CAC Certificate.pdf',
    businessRegistrationNumber: 'RC-1234567',
  },
  {
    id: 'VND-002',
    businessName: 'Coastal Paradise Resort',
    ownerName: 'Ada Williams',
    email: 'ada@coastalparadise.com',
    phone: '+234 802 345 6789',
    category: 'Accommodation',
    location: 'Port Harcourt, Nigeria',
    onboardingDate: '2024-10-20',
    status: 'Approved',
    verificationStatus: 'Verified',
    totalListings: 12,
    completionPercentage: 100,
    businessDocument: 'Business License.pdf',
    businessRegistrationNumber: 'RC-2345678',
  },
  {
    id: 'VND-003',
    businessName: 'Lagos Food Tours',
    ownerName: 'Chidi Obi',
    email: 'chidi@lagosfoodtours.com',
    phone: '+234 803 456 7890',
    category: 'Food & Dining',
    location: 'Lagos, Nigeria',
    onboardingDate: '2024-10-25',
    status: 'Under Review',
    verificationStatus: 'Additional Info Required',
    totalListings: 0,
    completionPercentage: 85,
    businessDocument: 'Pending',
    businessRegistrationNumber: 'RC-3456789',
  },
  {
    id: 'VND-004',
    businessName: 'Heritage Tours Nigeria',
    ownerName: 'Fatima Hassan',
    email: 'fatima@heritagetours.ng',
    phone: '+234 804 567 8901',
    category: 'Tours & Travel',
    location: 'Abuja, Nigeria',
    onboardingDate: '2024-10-28',
    status: 'Approved',
    verificationStatus: 'Verified',
    totalListings: 8,
    completionPercentage: 100,
    businessDocument: 'CAC Certificate.pdf',
    businessRegistrationNumber: 'RC-4567890',
  },
  {
    id: 'VND-005',
    businessName: 'Peak Explorers',
    ownerName: 'Emmanuel Nwankwo',
    email: 'emmanuel@peakexplorers.com',
    phone: '+234 805 678 9012',
    category: 'Adventure & Sports',
    location: 'Enugu, Nigeria',
    onboardingDate: '2024-11-01',
    status: 'Rejected',
    verificationStatus: 'Invalid Documents',
    totalListings: 0,
    completionPercentage: 75,
    businessDocument: 'Rejected',
    businessRegistrationNumber: 'Invalid',
  },
  {
    id: 'VND-006',
    businessName: 'Royal Car Rentals',
    ownerName: 'Blessing Ade',
    email: 'blessing@royalcarrentals.ng',
    phone: '+234 806 789 0123',
    category: 'Transportation',
    location: 'Lagos, Nigeria',
    onboardingDate: '2024-11-02',
    status: 'Pending Approval',
    verificationStatus: 'Documents Submitted',
    totalListings: 0,
    completionPercentage: 100,
    businessDocument: 'Business License.pdf',
    businessRegistrationNumber: 'RC-5678901',
  },
];
